In [4]:
# 1. Import the Numpy package under the name np
import numpy as np

In [5]:
# 2. Create a null vector of size 10
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# 3. Create a null vector of size 10 but the fifth value which is 1
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# 4. Create a vector with values ranging from 10 to 49
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 5. Reverse a vector (the first element becomes last)
# I used the vector from the fourth question
x = np.arange(10, 50)
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
# 6. Create a 3x3 matrix with values ranging from 0 to 8
x = np.arange(0, 9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# 7. Find indices of nonzero elements from [1,2,0,0,4,0]
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

In [11]:
# 8. Create a 3x3x3 array with random values
x = np.random.random((3, 3, 3))
print(x)

[[[0.35371242 0.08881712 0.42028406]
  [0.09714178 0.41965879 0.85043467]
  [0.06411627 0.3028978  0.42423625]]

 [[0.36408761 0.57973974 0.99598178]
  [0.04983121 0.50517634 0.60624004]
  [0.01838227 0.76630041 0.80763066]]

 [[0.3124024  0.35464021 0.90094141]
  [0.01259987 0.93980119 0.60317641]
  [0.13023887 0.69124214 0.76202383]]]


In [12]:
# 9. Create a random vector of size 30 and find the mean value
x = np.random.random(30)
x.sort()
m = x.mean()
print(m)

0.45842063600464616


In [13]:
# 10. Create a 2d array with 1 on the border and 0 inside
x = np.ones((4, 4))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [14]:
# 11. Create an 8x8 matrix and fill it with a checkerboard pattern
x = np.array([[0, 1], [1, 0]])
y = np.tile(x, (8, 8))
print(y)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


In [15]:
# 12. What is the major difference between sets, lists, tuples 
# and dictionaries?

Answer:
Lists are used to store multiple items in a single variable and are mutable, tuples are used for the same purpose but are immutable.
Dictionaries are used to store data values in key-value pairs. 
Does not allow duplicates, it is a collection that is unordered and changeable.
Sets are used to store multiple items in a single variable. 
A difference from dictionaries is that set is a collection that is both unordered and unindexed.

In [16]:
# 13. Print first 10 natural numbers using while loop
i =1
while(i <= 10):
    print(i)
    i = i+1

1
2
3
4
5
6
7
8
9
10


In [17]:
# 14. Print the numbers -10 to -1 using for loop.
for i in range(-10, 0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [19]:
# 15. Print the message “Done” after successful execution of any for a loop. 
for i in range(-10, 0):
    print(i)
print("Done")

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
Done


In [20]:
# 16. Create a random vector of size 10 and sort it
x = np.random.random(10)
x.sort()
print(x)

[0.02282135 0.16191328 0.1676704  0.17895628 0.20474919 0.22702076
 0.67789694 0.81395663 0.86109799 0.92018727]


In [21]:
# 17. Execute any three math functions using NumPy.
# subtract elements
np.subtract(4, 10)

-6

In [22]:
# add elements
np.add(-13, 16)

3

In [23]:
# multiply elements
np.multiply(15, 15)

225